- name: Copy Dispatch Service file
  ansible.builtin.template:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service

- name: Install GoLang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Load App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prerequisites

- name: Copy Download Application Dependencies
  ansible.builtin.shell: go mod init dispatch; go get; go build
  args:
    chdir: /app

- name: Start Application Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup